/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#ffffff',
        secondary: '#c8c6c5',
        accent: '#6D5DFC',
        'accent-secondary': '#00D4FF',
        text: '#e2e2e2',
        'text-muted': '#A0AEC0',
        success: '#22C55E',
        danger: '#EF4444',
        'glass-border-hover': 'rgba(255, 255, 255, 0.30)',
        'glass-fill': 'rgba(255, 255, 255, 0.03)',
        'primary-fixed-dim': '#c6c6c7',
        'on-tertiary-container': '#626566',
        'primary-container': '#e2e2e2',
        'on-primary-fixed-variant': '#454747',
        'tertiary-container': '#e0e3e4',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed-variant': '#444748',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#636565',
        'background': '#131313',
        'surface-container-low': '#1b1b1b',
        'on-primary': '#2f3131',
        'on-surface-muted': 'rgba(226, 226, 226, 0.70)',
        'on-tertiary': '#2d3132',
        'on-surface-variant': '#c4c7c8',
        'on-secondary-fixed-variant': '#474746',
        'surface-container-highest': '#353535',
        'secondary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#191c1d',
        'on-error': '#690005',
        'glass-hover': 'rgba(255, 255, 255, 0.06)',
        'primary-fixed': '#e2e2e2',
        'surface-dim': '#131313',
        'tertiary': '#ffffff',
        'inverse-surface': '#e2e2e2',
        'error': '#ffb4ab',
        'glass-border': 'rgba(255, 255, 255, 0.10)',
        'on-secondary-container': '#b6b5b4',
        'surface-variant': '#353535',
        'outline-variant': '#444748',
        'on-surface': '#e2e2e2',
        'on-primary-fixed': '#1a1c1c',
        'surface-tint': '#c6c6c7',
        'tertiary-fixed': '#e0e3e4',
        'on-background': '#e2e2e2',
        'surface-container-lowest': '#0e0e0e',
        'outline': '#8e9192',
        'surface-bright': '#393939',
        'on-secondary-fixed': '#1b1c1b',
        'on-secondary': '#303030',
        'inverse-primary': '#5d5f5f',
        'surface': '#131313',
        'inverse-on-surface': '#303030',
        'tertiary-fixed-dim': '#c4c7c8',
        'surface-container': '#1f1f1f',
        'secondary-fixed': '#e4e2e1',
        'secondary-container': '#474746',
        'error-container': '#93000a'
      },
      backdropBlur: {
        xl: '20px',
      },
      animation: {
        shimmer: 'shimmer 2s infinite',
        'fade-in': 'fadeIn 0.3s ease-in',
        'slide-up': 'slideUp 0.3s ease-out',
        'bounce-light': 'bounceLight 2s infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        bounceLight: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-2px)' },
        },
      },
    },
  },
  plugins: [],
};
