'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronRight, ChevronLeft, BookOpen } from 'lucide-react';

export default function BookPreview({ data, coverTitle, coverSubtitle, theme }) {
  const [currentPage, setCurrentPage] = useState(0);

  // Group memories into pages (simple logic: 2 per page, or 1 large one)
  const pages = [];
  
  // Page 0: Cover
  pages.push({
    type: 'cover',
    title: coverTitle || 'My Legacy',
    subtitle: coverSubtitle || 'A Journey in Memories',
    year: new Date().getFullYear(),
  });

  // Page 1: Intro/Dedication
  pages.push({
    type: 'text',
    title: 'Dedication',
    content: 'This book is a collection of memories, milestones, and moments that shaped my journey. Generated by Legacy OS AI.',
  });

  // Subsequent pages based on data
  if (data && data.length > 0) {
    let i = 0;
    while (i < data.length) {
      const mem1 = data[i];
      const mem2 = i + 1 < data.length ? data[i + 1] : null;

      // For simplicity in this demo, just put 1-2 memories per page
      pages.push({
        type: 'content',
        items: mem2 ? [mem1, mem2] : [mem1],
      });
      i += 2;
    }
  }

  // Page N: Back Cover
  pages.push({
    type: 'backcover',
  });

  const next = () => setCurrentPage(prev => Math.min(prev + 1, pages.length - 1));
  const prev = () => setCurrentPage(prev => Math.max(prev - 1, 0));

  const page = pages[currentPage];

  // Theme styles (simulating print styles)
  const themeStyles = {
    minimal: 'bg-white text-zinc-900 font-sans',
    classic: 'bg-[#f4f1ea] text-stone-900 font-serif',
    modern: 'bg-zinc-900 text-white font-sans',
  };

  const currentThemeStyle = themeStyles[theme] || themeStyles.classic;

  return (
    <div className="w-full flex flex-col items-center">
      
      {/* 3D Book Container */}
      <div className="relative w-full max-w-[500px] md:max-w-[800px] aspect-[1/1.4] md:aspect-[2/1.4] perspective-[2000px] mx-auto mb-8">
        
        <AnimatePresence mode="wait">
          <motion.div
            key={currentPage}
            initial={{ rotateY: currentPage > 0 ? 90 : -90, opacity: 0 }}
            animate={{ rotateY: 0, opacity: 1 }}
            exit={{ rotateY: currentPage > 0 ? -90 : 90, opacity: 0 }}
            transition={{ duration: 0.5, ease: "easeInOut" }}
            className={`absolute inset-0 shadow-2xl overflow-hidden origin-left md:origin-center ${
              currentPage === 0 || currentPage === pages.length - 1 ? 'rounded-r-xl' : ''
            }`}
            style={{ transformStyle: 'preserve-3d' }}
          >
            {/* The actual page rendering */}
            <div className={`w-full h-full flex ${currentThemeStyle}`}>
              
              {/* Single page for mobile, double page for desktop (except cover) */}
              <div className={`w-full h-full flex ${currentPage === 0 || currentPage === pages.length - 1 ? '' : 'md:flex-row'}`}>
                
                {/* Book Spine Shadow */}
                <div className="absolute inset-y-0 left-0 w-8 bg-gradient-to-r from-black/20 to-transparent z-10 pointer-events-none md:hidden" />
                <div className="hidden md:block absolute inset-y-0 left-1/2 -translate-x-1/2 w-16 bg-gradient-to-r from-transparent via-black/10 to-transparent z-10 pointer-events-none" />

                {/* Render Cover */}
                {page.type === 'cover' && (
                  <div className="w-full h-full flex flex-col items-center justify-center p-12 text-center relative border-l-8 border-los-accent/50 bg-[#1a1a1a] text-white">
                    <div className="absolute top-8 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-los-accent to-transparent opacity-50" />
                    <BookOpen size={48} className="text-los-accent mb-12 opacity-50" />
                    <h1 className="text-5xl md:text-7xl font-serif font-bold mb-4 tracking-tight leading-none">{page.title}</h1>
                    <p className="text-xl text-white/60 uppercase tracking-[0.3em] font-light">{page.subtitle}</p>
                    <div className="absolute bottom-12 text-sm text-white/40 tracking-widest">{page.year}</div>
                  </div>
                )}

                {/* Render Text Page */}
                {page.type === 'text' && (
                  <div className="w-full h-full flex flex-col items-center justify-center p-12 text-center md:w-1/2 mx-auto">
                    <h2 className="text-2xl font-serif font-bold mb-8 italic">{page.title}</h2>
                    <p className="text-lg leading-relaxed opacity-80">{page.content}</p>
                  </div>
                )}

                {/* Render Content Page (Memories) */}
                {page.type === 'content' && (
                  <>
                    {/* Left Page (Mobile = only page) */}
                    <div className="w-full md:w-1/2 h-full p-8 md:p-12 flex flex-col justify-center border-r border-black/5">
                      {page.items[0] && (
                        <div className="h-full flex flex-col justify-center">
                          {page.items[0].url && (
                            <div className="w-full aspect-[4/3] mb-6 shadow-md border-4 border-white overflow-hidden bg-black/5">
                              <img src={page.items[0].url} alt="" className="w-full h-full object-cover grayscale-[20%]" />
                            </div>
                          )}
                          <div className="text-center">
                            <h3 className="text-xl font-bold mb-2 font-serif">{page.items[0].title}</h3>
                            <p className="text-[10px] uppercase tracking-widest opacity-50 mb-4">
                              {new Date(page.items[0].date || page.items[0].createdAt).toLocaleDateString()}
                            </p>
                            <p className="text-sm opacity-80 leading-relaxed">
                              {page.items[0].description || page.items[0].content}
                            </p>
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Right Page (Desktop only) */}
                    <div className="hidden md:flex w-1/2 h-full p-12 flex-col justify-center relative">
                      {page.items[1] ? (
                        <div className="h-full flex flex-col justify-center">
                          {page.items[1].url && (
                            <div className="w-full aspect-[4/3] mb-6 shadow-md border-4 border-white overflow-hidden bg-black/5">
                              <img src={page.items[1].url} alt="" className="w-full h-full object-cover grayscale-[20%]" />
                            </div>
                          )}
                          <div className="text-center">
                            <h3 className="text-xl font-bold mb-2 font-serif">{page.items[1].title}</h3>
                            <p className="text-[10px] uppercase tracking-widest opacity-50 mb-4">
                              {new Date(page.items[1].date || page.items[1].createdAt).toLocaleDateString()}
                            </p>
                            <p className="text-sm opacity-80 leading-relaxed">
                              {page.items[1].description || page.items[1].content}
                            </p>
                          </div>
                        </div>
                      ) : (
                        <div className="w-full h-full flex items-center justify-center">
                          <div className="w-8 h-px bg-black/20" />
                        </div>
                      )}
                      
                      {/* Page number */}
                      <div className="absolute bottom-6 right-8 text-xs font-mono opacity-30">
                        {currentPage * 2}
                      </div>
                    </div>
                  </>
                )}

                {/* Render Back Cover */}
                {page.type === 'backcover' && (
                  <div className="w-full h-full flex flex-col items-center justify-center p-12 text-center bg-[#1a1a1a] text-white/50">
                    <BookOpen size={24} className="mb-4 opacity-20" />
                    <p className="text-xs uppercase tracking-widest">Legacy OS Press</p>
                    <div className="mt-8 w-32 h-12 bg-white/10 rounded" /> {/* Barcode mockup */}
                  </div>
                )}

              </div>
            </div>
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Navigation Controls */}
      <div className="flex items-center gap-6">
        <button 
          onClick={prev} 
          disabled={currentPage === 0}
          className="p-3 rounded-full bg-los-card border border-los-border text-white hover:bg-los-bg-secondary disabled:opacity-30 transition-colors"
        >
          <ChevronLeft size={20} />
        </button>
        
        <span className="text-sm font-medium text-los-text-muted font-mono">
          Page {currentPage + 1} / {pages.length}
        </span>
        
        <button 
          onClick={next} 
          disabled={currentPage === pages.length - 1}
          className="p-3 rounded-full bg-los-card border border-los-border text-white hover:bg-los-bg-secondary disabled:opacity-30 transition-colors"
        >
          <ChevronRight size={20} />
        </button>
      </div>
    </div>
  );
}
