-- SUPERSEDED: Legacy OS moved from MySQL to Supabase-hosted Postgres.
--
-- The real, current schema lives as ordered Supabase migrations in:
--   ../supabase/migrations/*.sql
--
-- Apply them with the Supabase CLI against your project:
--   npx supabase link --project-ref <your-project-ref>
--   npx supabase db push
--
-- This file is kept only so old bookmarks/links don't 404; it no longer reflects the running
-- schema and must not be imported into a MySQL server for a current deployment.
